language: python
python:
  - "2.7"
  - "3.5"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install .
  - pip install -U pytest
  - pip install pytest-cov tempdir>=0.7.1 future codecov
# command to run tests
script:
  - pytest --cov=PI_build
  - codecov
